### ISSUE TITLE
Figure out the exact meaning of sync in transition systems

### ISSUE THREAD

**Issue by magoorden** [Ecdar/j-Ecdar#33]
In simple transition systems we have the set of actions `inputs`, `outputs`, and `syncs`. Since there is no documentation and the theory only talks about input and output actions, the purpose and assumptions about `syncs` is not that clear.

**Comment by Brandhoej** [comment]
I found that syncs were used in compositions to describe the set of channels which can both be found as an input and output in the final composition. They have been removed in #59, and instead the input/output sets are now calculated differently for compositions.
