### ISSUE TITLE
Reduce conversion between guards and CDDs

### ISSUE THREAD

**Issue by florber** [Ecdar/j-Ecdar#50]
For each CDD, store the corresponding guard structure and only recompute it when the CDD is transformed or updated. This might require some restructuring, as I assume sometimes new CDDs are created instead of updating one, when keeping the same one would do the trick as well.

**Comment by Brandhoej** [comment]
A reduction has been introduced in #58 by replacing the usages of CDD.toGuardList to CDD.getGuard which lazily creates the corresponding Guard and only a new one if the CDD has changed. Addtionally, the extraction result utilises the same technique.
