### ISSUE TITLE
Build #38 failed

### ISSUE THREAD

**Issue by magoorden** [Ecdar/j-Ecdar#85]
The latest CI build fails with the following error:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> Process 'Gradle Test Executor 2' finished with non-zero exit value 134
  This problem might be caused by incorrect test process configuration.
  Please refer to the test execution section in the User Manual at https://docs.gradle.org/7.1/userguide/java_testing.html#sec:test_execution
```

**Comment by Brandhoej** [comment]
This was caused by an internal cdd library call, which was "solved" by rerunning the tests.
![ci cdd fatal error](https://user-images.githubusercontent.com/58144556/198897750-608dbe1f-0aec-4fc6-bb9e-9ff10b0ed896.PNG)

**Comment by magoorden** [comment]
Do you think we need to do something on this issue, or is it sufficient to close this one in order to archive it for future reference when such an error occurs again?

**Comment by Brandhoej** [comment]
I have opened #90 which provides a direction for debugging this issue and a possible cause.
